# Generated by Django 3.1.3 on 2020-12-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
    ]
